[build]
  publish = "."

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/assets/artworks/*"
  [headers.values]
    Cache-Control = "no-cache"

[[redirects]]
  from = "/studio"
  to = "/studio.html"
  status = 200

[[redirects]]
  from = "/studio/"
  to = "/studio.html"
  status = 200
